In [1]:
import numpy as np 
from numpy import ndarray

In [2]:
def matmul(a: ndarray, b: ndarray) -> ndarray: 
    # Number of columns of a must be equal to the number of rows of b.
    if a.shape[1] == b.shape[0]: 
       c = np.matmul(a,b)
       #print(c)
       return c
    else: 
        print(f"multiplying matrix \n{a} and \n{b} not possible as shapes are incompatible")
        return None

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.array([[1,1,0],[0,1,1],[1,0,1]])

In [4]:
print(matmul(a,b))

[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


In [5]:
c = np.array([[1,2],[4,5],[6,7]]) 
d = np.array([[1,1,0], [0,1,1], [1,0,1]])

print(matmul(c,d))

multiplying matrix 
[[1 2]
 [4 5]
 [6 7]] and 
[[1 1 0]
 [0 1 1]
 [1 0 1]] not possible as shapes are incompatible
None


In [6]:
print(matmul(b,a))

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [7]:
e = np.array([[1,2,1,2],[4,1,-1,-4]])
f = np.array([[0,3], 
              [1,-1], 
              [2,1], 
              [5,2]])

print(matmul(e,f))

[[ 14   6]
 [-21   2]]


In [8]:
matmul(f,e)

array([[ 12,   3,  -3, -12],
       [ -3,   1,   2,   6],
       [  6,   5,   1,   0],
       [ 13,  12,   3,   2]])

In [9]:
"""
Solving the series of equations 
x1 + x2 + x3 = 3 
x1 - x2 + 2x3 = 2 
     x2 + x3 = 2 

    ans = inv(X) x Y 
    This can be solved if X is not a singular array which means: 
    2 equations in X is not a linear combination of another array
"""

x = np.array([[1,1,1], [1,-1,2],[0,1,1]])
y = np.array([[3],[2],[2]])

matmul(np.linalg.inv(x), y) 

array([[1.],
       [1.],
       [1.]])

In [10]:
x1 = np.array([[4,5], [2, -4]])
x2 = np.array([[5],[1]])

ans = matmul (np.linalg.inv(x1), x2) 
ans

array([[0.96153846],
       [0.23076923]])

In [11]:
x3 = np.array([[1,2,3], [3, 2, 1]])
x4 = np.array([[0,2],[1,-1],[0,1]])

ans = matmul (x3,x4) 
print(f"AB = {ans}")

print(f"BA = {matmul(x4,x3)}")

AB = [[2 3]
 [2 5]]
BA = [[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


In [12]:
def isSingularMatrix(a: ndarray) -> bool: 
    det = np.linalg.det(a)
    if det == 0.0:
        return True
    else: 
        return False

In [13]:
a = np.array([[1,1,1],[1, -1, 2],[2,0,3]])

if isSingularMatrix(a) : 
    print(f"Matrix {a} is sigunlar")
else: 
    print(f"Matrix {a} is solvable")

Matrix [[ 1  1  1]
 [ 1 -1  2]
 [ 2  0  3]] is sigunlar


In [14]:
j = np.array([[2,3,5],[4,-2,-7],[9,5,-3]])
k = np.array([[1], [8],[2]])

if not(isSingularMatrix(j)): 
    l = matmul(np.linalg.inv(j), k)
    print(f"Solution to the equations is:\n {l}")
else:
    print(f"metric: {j} \nis singular")

Solution to the equations is:
 [[ 2.44537815]
 [-3.28571429]
 [ 1.19327731]]


In [15]:
# important formula when the matrix A is not square but we need solve for Ax=b  x = INV(T(A).A).T(A).b 
# here T(A) is transpose of A INV(A) is INV of A

l = np.array(([1,2,3],[3,4,5]))
o = np.array(([2,3,8],[1,1,2]))
lt = np.transpose(l)

ltli = np.linalg.inv(matmul(lt,l))
ltlilt = matmul(ltli, lt)
ans = matmul(ltlilt, o)
print(ans)


[[ -0.8125   -1.125    -2.875  ]
 [ -1.9375   -3.875   -11.625  ]
 [  2.59375   4.4375   12.5625 ]]


In [16]:
a = np.array([[0,2],[3,1]])
ai = np.linalg.inv(a)

print(ai)

[[-0.16666667  0.33333333]
 [ 0.5         0.        ]]


In [18]:
# given metric below find the inverse 
x = np.array([[2,3,4],[3,4,5],[4,5,6]])
xi = np.linalg.det(x)
print(xi)  # since the det of a matrix is 0 then it is not invertible and is singular. 

0.0


In [22]:
y = np.array([[1,0,1,0],[0,1,1,0],[1,1,0,1],[1,1,1,0]])
yd = np.linalg.det(y)
print(yd)

1.0


In [24]:
yi = np.linalg.inv(y)
print(yi)

[[ 0. -1.  0.  1.]
 [-1.  0.  0.  1.]
 [ 1.  1. -0. -1.]
 [ 1.  1.  1. -2.]]
