In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.23.5


In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(a.dtype)
print(a.shape)
print(a.ndim) # the dimension for the array 
print(a.itemsize)  # size of the element - 8 bytes per element. 

int64
(3,)
1
8


In [5]:
a[0] = 0 
print(a)

[0 2 3]


In [6]:
b = a * np.array([2,4,5])
print(b)

[ 0  8 15]


## Dot Product

In [7]:
# List 
l1 = [1,2,3] 
l2 = [4,5,6]

dot = 0 
for x in range(len(l1)): 
    dot += l1[x] * l2[x]

print(dot)

32


In [8]:
# numpy array 
a = np.array([1,2,3])
b = np.array([4,5,6])

dot = np.dot(a,b)
print(dot)

32


In [9]:
# alternative 
sum1 = a*b 
dot = np.sum(sum1)
print(dot)

32


In [10]:
dot = a @ b 
print(dot)

32


In [11]:
# multi dimentional array 

a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.shape) # 2 rows and 3 columns 

print(a[1,1])
print(a[:,0]) # prints the entire first column 
print(a[0,:]) # prints entire first row 

[[1 2 3]
 [4 5 6]]
(2, 3)
5
[1 4]
[1 2 3]


In [12]:
# transpose the array 
print(a.T)
print(a.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [13]:
# inverse 
a = np.array([[1,2], [3,4]])
print(f"inverse of array \n {a} : {np.linalg.inv(a)}")

print(f"determinant of \n {a} : {np.linalg.det(a)}")

inverse of array 
 [[1 2]
 [3 4]] : [[-2.   1. ]
 [ 1.5 -0.5]]
determinant of 
 [[1 2]
 [3 4]] : -2.0000000000000004


In [14]:
c = np.diag(a)
print(f"diagonal of \n{a} : \n{np.diag(c)}")

diagonal of 
[[1 2]
 [3 4]] : 
[[1 0]
 [0 4]]


## Slicing Array - Numpy 

In [15]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b = a[0,:]  # slice to get the first row of the a 
print(b)

# get the entire column 1 
print(f"Second column {a[:,1]}")

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]
Second column [2 6]


In [16]:
# boolean condition 
bool_idx = a > 2 
print(bool_idx)

[[False False  True  True]
 [ True  True  True  True]]


In [17]:
# we can apply the bool-idx to the array - returns a single dimension array. 
print(a[bool_idx])

[3 4 5 6 7 8]


In [18]:
# short form 
print(a[a>2])

[3 4 5 6 7 8]


In [19]:
# if you need the same array structure or shape then
b = np.where(a>2, a, -1)
print(b)

[[-1 -1  3  4]
 [ 5  6  7  8]]


In [20]:

a = np.array([10,19,30,31,43,51, 61])
print(a)
b = [1,3,5]
print(a[b])

[10 19 30 31 43 51 61]
[19 31 51]


In [21]:
even = np.argwhere(a%2==0).flatten()
print(a[even])  # get even numbers from the array. 

[10 30]


## Creating Numpy arrays 

In [22]:
a = np.arange(1,7)
print(a)

print(a.shape)

[1 2 3 4 5 6]
(6,)


In [23]:
# reshape the array 
b = a.reshape(2,3)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
# creating a new axis 
b = a[np.newaxis, :]
print(f"new axis on column {b}")
print(f"shape: {b.shape}")

new axis on column [[1 2 3 4 5 6]]
shape: (1, 6)


In [25]:
b = a[:,np.newaxis]
print(f"new axis on column \n{b}")
print(f"shape: {b.shape}")

new axis on column 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
shape: (6, 1)


### Some more Basic Indexing and Slicing 

In [26]:
m = np.arange(10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
m[5:8]

array([5, 6, 7])

In [29]:
m[5:8] = 12
print(m)

[ 0  1  2  3  4 12 12 12  8  9]


In [30]:
arr_silce = m[5:8]
arr_silce

array([12, 12, 12])

In [33]:
arr_silce[1] = 1234
m 

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [34]:
arr_silce[:] = 64
m

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## Transposing 

In [36]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [39]:
dot = np.dot(a.T,a)
print(dot)

[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [42]:
b = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(b)
b.T

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [43]:
dotb = np.dot(b, b.T)
print(dotb)

[[ 1  2  3  0  0]
 [ 2  9  8  1 -1]
 [ 3  8 49 -8  8]
 [ 0  1 -8  2 -2]
 [ 0 -1  8 -2  2]]


In [45]:
dotb = b @ b.T
dotb

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

### Pseudo Random number generation 

In [46]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[-0.82110182, -0.37800992,  1.02070411,  1.35665794],
       [ 0.1624295 , -0.88060208,  0.48462291,  1.03359139],
       [-0.03854407,  0.69119473,  0.99978647,  0.52050888],
       [ 0.48441902, -0.73854677, -1.70919635,  0.32410958]])