In [1]:
import numpy as np 
from numpy import ndarray

In [20]:
def matmul(a: ndarray, b: ndarray) -> ndarray: 
    # Number of columns of a must be equal to the number of rows of b.
    if a.shape[1] == b.shape[0]: 
       c = np.matmul(a,b)
       #print(c)
       return c
    else: 
        print(f"multiplying matrix \n{a} and \n{b} not possible as shapes are incompatible")
        return None

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.array([[1,1,0],[0,1,1],[1,0,1]])

In [22]:
print(matmul(a,b))

[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


In [23]:
c = np.array([[1,2],[4,5],[6,7]]) 
d = np.array([[1,1,0], [0,1,1], [1,0,1]])

print(matmul(c,d))

multiplying matrix 
[[1 2]
 [4 5]
 [6 7]] and 
[[1 1 0]
 [0 1 1]
 [1 0 1]] not possible as shapes are incompatible
None


In [24]:
print(matmul(b,a))

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [25]:
e = np.array([[1,2,1,2],[4,1,-1,-4]])
f = np.array([[0,3], 
              [1,-1], 
              [2,1], 
              [5,2]])

print(matmul(e,f))

[[ 14   6]
 [-21   2]]


In [26]:
matmul(f,e)

array([[ 12,   3,  -3, -12],
       [ -3,   1,   2,   6],
       [  6,   5,   1,   0],
       [ 13,  12,   3,   2]])

In [27]:
"""
Solving the series of equations 
x1 + x2 + x3 = 3 
x1 - x2 + 2x3 = 2 
     x2 + x3 = 2 

    ans = inv(X) x Y 
    This can be solved if X is not a singular array which means: 
    2 equations in X is not a linear combination of another array
"""

x = np.array([[1,1,1], [1,-1,2],[0,1,1]])
y = np.array([[3],[2],[2]])

matmul(np.linalg.inv(x), y) 

array([[1.],
       [1.],
       [1.]])

In [31]:
x1 = np.array([[4,5], [2, -4]])
x2 = np.array([[5],[1]])

ans = matmul (np.linalg.inv(x1), x2) 
ans

array([[0.96153846],
       [0.23076923]])

In [33]:
x3 = np.array([[1,2,3], [3, 2, 1]])
x4 = np.array([[0,2],[1,-1],[0,1]])

ans = matmul (x3,x4) 
print(f"AB = {ans}")

print(f"BA = {matmul(x4,x3)}")

AB = [[2 3]
 [2 5]]
BA = [[ 6  4  2]
 [-2  0  2]
 [ 3  2  1]]


In [39]:
def isSingularMatrix(a: ndarray) -> bool: 
    det = np.linalg.det(a)
    if det == 0.0:
        return True
    else: 
        return False

In [43]:
a = np.array([[1,1,1],[1, -1, 2],[2,0,3]])

if isSingularMatrix(a) : 
    print(f"Matrix {a} is sigunlar")
else: 
    print(f"Matrix {a} is solvable")

Matrix [[ 1  1  1]
 [ 1 -1  2]
 [ 2  0  3]] is sigunlar


In [47]:
# transpose is a function of np itself 
at = a.T
at

array([[ 1,  1,  2],
       [ 1, -1,  0],
       [ 1,  2,  3]])

In [68]:
s = x.shape[0]
id = np.eye(s)

m = matmul(x, np.linalg.inv(x))
mr = matmul(np.linalg.inv(x), x)
# the multiplication of AA(Inverse) is the identity metric
print(f"AAInverse is identity: {np.allclose(id,m)} AInverseA is identity {np.allclose(m,id)}")

AAInverse is identity: True AInverseA is identity True
