In [8]:
import numpy as np 
from numpy import ndarray

In [45]:
def matmul(a: ndarray, b: ndarray): 
    # Number of columns of a must be equal to the number of rows of b.
    if a.shape[1] == b.shape[0]: 
       c = np.matmul(a,b)
       print(c)
    else: 
        print(f"multiplying matrix \n{a} and \n{b} not possible as shapes are incompatible")

In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
b = np.array([[1,1,0],[0,1,1],[1,0,1]])

In [47]:
matmul(a,b)

[[ 4  3  5]
 [10  9 11]
 [16 15 17]]


In [48]:
c = np.array([[1,2],[4,5],[6,7]]) 
d = np.array([[1,1,0], [0,1,1], [1,0,1]])

matmul(c,d)

multiplying matrix 
[[1 2]
 [4 5]
 [6 7]] and 
[[1 1 0]
 [0 1 1]
 [1 0 1]] not possible as shapes are incompatible


In [49]:
matmul(b,a)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [51]:
e = np.array([[1,2,1,2],[4,1,-1,-4]])
f = np.array([[0,3], 
              [1,-1], 
              [2,1], 
              [5,2]])

matmul(e,f)

[[ 14   6]
 [-21   2]]


In [52]:
matmul(f,e)

[[ 12   3  -3 -12]
 [ -3   1   2   6]
 [  6   5   1   0]
 [ 13  12   3   2]]
