In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.25.0


### Mertics and Slicing 

In [4]:
M = np.array([[0,2,3], [4,0,5], [6,7,0]])
M.shape

(3, 3)

In [5]:
# to get the first row 
M[0]

array([0, 2, 3])

In [6]:
# get the first row 
M[:,0]

array([0, 4, 6])

In [8]:
# get a section of the metrics - top left corner
M[:2,:2]

array([[0, 2],
       [4, 0]])

In [10]:
# get bottom right corner 
M[1:,1:]

array([[0, 5],
       [7, 0]])

In [11]:
# get top right corner 
M[:2,1:]

array([[2, 3],
       [0, 5]])

In [14]:
# get the bottom left coroner 
M[1:,:2]

array([[4, 0],
       [6, 7]])

### Ranges and Reshape

In [3]:
a = np.arange(1,7)
print(a)

print(a.shape)

[1 2 3 4 5 6]
(6,)


In [4]:
# reshape the array 
b = a.reshape(2,3)
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
# creating a new axis 
b = a[np.newaxis, :]
print(f"new axis on column {b}")
print(f"shape: {b.shape}")

new axis on column [[1 2 3 4 5 6]]
shape: (1, 6)


In [6]:
b = a[:,np.newaxis]
print(f"new axis on column \n{b}")
print(f"shape: {b.shape}")

new axis on column 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
shape: (6, 1)


## Concatenation

The np array is always represented as (row, column) which means first dimension is always the row and the second on is alaways the column. 
All the arrays given below are of 1 or 2 dimensions. The array a is of dimension 1 as we have entires only in a single row. Therefore we have a single dimension. All others have mutliple rows therefore they are spread across multiple dimensions. 

Also remember that we cannot concatenate arrays that do not have the same number dimensions. 
So we cannot concatenate a with any of the other arrays. 

In [16]:
# Shape of the arrays 
print(f"shape a: {np.shape(a)}")
print(f"shape b: {np.shape(b)}")
print(f"shape c: {np.shape(c)}")
print(f"shape d: {np.shape(d)}")
print(f"shape e: {np.shape(e)}")

# point to note that c and d must have same dimentions other wise this does not work 
print(f"dim a: {np.ndim(a)}")
print(f"dim b: {np.ndim(b)}")
print(f"dim c: {np.ndim(c)}")
print(f"dim d: {np.ndim(d)}")
print(f"dim e: {np.ndim(e)}")

shape a: (6,)
shape b: (6, 1)
shape c: (2, 2)
shape d: (1, 2)
shape e: (3, 2)
dim a: 1
dim b: 2
dim c: 2
dim d: 2
dim e: 2


In [31]:

c = np.array([[1,2],[3,4]])
d = np.array([[5,6]]) 

e = np.concatenate((c,d), axis=0)
print(e)


[[1 2]
 [3 4]
 [5 6]]


In [32]:
# if we want to concatenate c and d along axis = 1 we will have to transpose d
e = np.concatenate((c,d.T), axis=1)
print(e)
print(f"shape of e: {e.shape}")

[[1 2 5]
 [3 4 6]]
shape of e: (2, 3)


In [33]:
# now let us concantenate b and c and we get an error that dimensions along the axis must exactly match.
# if you are concatenating along the columns that the columns must match and if you are doing rows that rows must match. 
try: 
    f = np.concatenate((b,c), axis=1)
    print(f)
except ValueError as er: 
    print(er)


all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 6 and the array at index 1 has size 2


In [35]:
# hstack and vstack 
g = np.array([1,2,3,4])
h = np.array([5,6,7,8])

i = np.hstack((g,h))
print(i)

[1 2 3 4 5 6 7 8]


In [36]:
i = np.vstack((g,h))
print(i)

[[1 2 3 4]
 [5 6 7 8]]


## Broadcasting 

In [60]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([1,0,1])
z = x + y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


## Functions - Sum Mean 

* Axis = 0 means aggregate or perform actions along each of the columns 
* Axis = 1 means aggregate or perform actions along each of the rows

In [61]:
m = np.array([[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])

np.sum(m, axis=None)

203

In [62]:
np.sum(m, axis=0)

array([23, 25, 27, 29, 31, 33, 35])

In [63]:
np.sum(m,axis=1)

array([ 77, 126])

In [64]:
print(np.mean(m, axis=None))

14.5


In [65]:
print(np.mean(m,axis=0))

[11.5 12.5 13.5 14.5 15.5 16.5 17.5]


In [66]:
print(np.mean(m,axis=1))

[11. 18.]


### Standard Deviation or Variance 

In [67]:
print(m)

[[ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [68]:

print(np.var(m,axis=None))

16.25


In [69]:
print(np.var(m,axis=0))

[12.25 12.25 12.25 12.25 12.25 12.25 12.25]


In [70]:
print(np.var(m,axis=1))

[4. 4.]


In [71]:
print(np.std(m,axis=None))

4.031128874149275


In [72]:
print(np.std(m,axis=0))

[3.5 3.5 3.5 3.5 3.5 3.5 3.5]


In [73]:
print(np.std(m,axis=1))

[2. 2.]


### Min and Max 

In [74]:
print(m)

[[ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [75]:
print(np.min(m,axis=None))

8


In [76]:
print(np.min(m,axis=0))

[ 8  9 10 11 12 13 14]


In [77]:
print(np.min(m,axis=1))

[ 8 15]


## Dot Product 

In [86]:
j = np.array([[5,6,7,8,9]])
w = np.array([[.5],[.2],[.1],[.1],[.9]])

if j.shape[1] == w.shape[0]: 
    print(f"Shapes of {j} and \n{w} \n are good for dot product")
    dot = np.dot(j,w)
    print(dot)
else: 
    print(f"shapes of {j} and {w} are good for dot product operation")

Shapes of [[5 6 7 8 9]] and 
[[0.5]
 [0.2]
 [0.1]
 [0.1]
 [0.9]] 
 are good for dot product
[[13.3]]


## Copying NP arrays

In [96]:
# let look at copy and refernece 
k = np.array([1,2,3])
l = k 
print(f"l: {l} k: {k}")

l[0] = 30
print(f"l: {l} k: {k}")
print(k.dtype)
# here you see that l and k share a reference and therefore this is not a copy or is infact a shallow copy. 

l: [1 2 3] k: [1 2 3]
l: [30  2  3] k: [30  2  3]
int64


In [90]:
k = np.array([1,2,3])
l = np.copy(k) 
print(f"l: {l} k: {k}")

l[0] = 30
print(f"l: {l} k: {k}")
# here you can see that l is a copy of k and has its own memory. 

l: [1 2 3] k: [1 2 3]
l: [30  2  3] k: [1 2 3]


## Generating Arrays 

In [92]:
## following creates an array of all zeros of 2 rows and 3 columns 
n = np.zeros((2,3))
n 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [97]:
n = np.ones((2,3), dtype="int64") # specify the right data type. 
n

array([[1, 1, 1],
       [1, 1, 1]])

In [98]:
n = np.full((2,3), 5.0)
n 

array([[5., 5., 5.],
       [5., 5., 5.]])

In [99]:
# get an identity metrics 
n = np.eye(3)
n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
# creating a range of numbers on a one dimension array 
n = np.arange(15)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [105]:
n = np.linspace(0,19,6)  # ask for creating of 0,19 line and divide it into 6 parts. 
n

array([ 0. ,  3.8,  7.6, 11.4, 15.2, 19. ])

## Random Numbers 

In [131]:
p = np.random.random((3,2))  # given mean ~ 1 and var ~ 0 
p

array([[0.49917341, 0.05505456],
       [0.30755431, 0.32574543],
       [0.6335017 , 0.07042053]])

In [132]:
np.var(p) 

0.04382074658722652

In [133]:
np.mean(p)

0.3152416583527539

In [134]:
p = np.random.randn(3,2)  # normal or gaussian distribution - generally gives values with mean ~ 0 and var ~ 1
p

array([[ 0.16510848,  0.44871592],
       [-0.27396055,  0.22912425],
       [ 1.92532457, -1.81639866]])

In [135]:
np.mean(p)

0.1129856674104353

In [136]:
np.var(p)

1.2142905527680838

In [140]:
p = np.random.randint(10, size=(3,3))
p

array([[4, 4, 6],
       [3, 2, 9],
       [3, 2, 3]])

In [141]:
np.mean(p)

4.0

In [142]:
np.var(p)

4.444444444444445